#ifndef NJD_SET_ACCENT_TYPE_RULE_H
#define NJD_SET_ACCENT_TYPE_RULE_H

#ifdef __cplusplus
#define NJD_SET_ACCENT_TYPE_RULE_H_START extern "C" {
#define NJD_SET_ACCENT_TYPE_RULE_H_END   }
#else
#define NJD_SET_ACCENT_TYPE_RULE_H_START
#define NJD_SET_ACCENT_TYPE_RULE_H_END
#endif                          /* __CPLUSPLUS */

NJD_SET_ACCENT_TYPE_RULE_H_START;

#define NJD_SET_ACCENT_TYPE_KAZU "数"
#define NJD_SET_ACCENT_TYPE_ICHI "一"
#define NJD_SET_ACCENT_TYPE_NI "二"
#define NJD_SET_ACCENT_TYPE_SAN "三"
#define NJD_SET_ACCENT_TYPE_YON "四"
#define NJD_SET_ACCENT_TYPE_GO "五"
#define NJD_SET_ACCENT_TYPE_ROKU "六"
#define NJD_SET_ACCENT_TYPE_NANA "七"
#define NJD_SET_ACCENT_TYPE_HACHI "八"
#define NJD_SET_ACCENT_TYPE_KYUU "九"
#define NJD_SET_ACCENT_TYPE_JYUU "十"
#define NJD_SET_ACCENT_TYPE_HYAKU "百"
#define NJD_SET_ACCENT_TYPE_SEN "千"
#define NJD_SET_ACCENT_TYPE_MAN "万"
#define NJD_SET_ACCENT_TYPE_OKU "億"
#define NJD_SET_ACCENT_TYPE_CHOU "兆"
#define NJD_SET_ACCENT_TYPE_SUU "数"
#define NJD_SET_ACCENT_TYPE_NAN "何"
#define NJD_SET_ACCENT_TYPE_IKU "幾"

NJD_SET_ACCENT_TYPE_RULE_H_END;

#endif                          /* !NJD_SET_ACCENT_TYPE_RULE_H */
